from tests.terminal_run_continuation_authority_cases import (
    test_eligibility_rejects_forged_resource_authority as test_eligibility_rejects_forged_resource_authority,
    test_eligibility_rejects_linked_output_project as test_eligibility_rejects_linked_output_project,
    test_resolve_uses_read_only_existing_resource_authority as test_resolve_uses_read_only_existing_resource_authority,
)
from tests.terminal_run_continuation_lock_cases import (
    test_partial_cleanup_never_unlinks_post_validation_replacement as test_partial_cleanup_never_unlinks_post_validation_replacement,
    test_active_lock_revalidates_path_after_handle_check as test_active_lock_revalidates_path_after_handle_check,
    test_lock_atomic_concurrent_acquisition_has_one_owner as test_lock_atomic_concurrent_acquisition_has_one_owner,
    test_lock_duplicate_or_stale_owner_is_never_broken as test_lock_duplicate_or_stale_owner_is_never_broken,
    test_lock_is_external_exclusive_and_context_managed as test_lock_is_external_exclusive_and_context_managed,
    test_lock_keeps_owner_handle_open_for_claim_lifetime as test_lock_keeps_owner_handle_open_for_claim_lifetime,
    test_release_never_unlinks_post_validation_replacement as test_release_never_unlinks_post_validation_replacement,
)
from tests.terminal_run_continuation_lifecycle_cases import (
    test_child_summary_records_lineage_with_independent_outcome as test_child_summary_records_lineage_with_independent_outcome,
    test_continuation_prompt_context_is_bounded_and_path_free as test_continuation_prompt_context_is_bounded_and_path_free,
    test_phase2_eligible_attachment_pins_verified_container_id as test_phase2_eligible_attachment_pins_verified_container_id,
    test_required_child_seal_failure_is_not_published_as_pass as test_required_child_seal_failure_is_not_published_as_pass,
    test_required_child_seal_rejected_artifact_is_not_published_as_pass as test_required_child_seal_rejected_artifact_is_not_published_as_pass,
)
from tests.terminal_run_continuation_hydration_cases import (
    test_anchor_matrix_hydrates_only_successful_canonical_predecessors as test_anchor_matrix_hydrates_only_successful_canonical_predecessors,
    test_hydrate_rejects_failed_predecessor as test_hydrate_rejects_failed_predecessor,
    test_hydrate_rejects_missing_canonical_output as test_hydrate_rejects_missing_canonical_output,
    test_hydrate_rejects_unknown_anchor as test_hydrate_rejects_unknown_anchor,
    test_hydrate_rejects_ambiguous_anchor as test_hydrate_rejects_ambiguous_anchor,
    test_hydrate_rejects_workflow_digest_drift as test_hydrate_rejects_workflow_digest_drift,
    test_hydrate_rejects_canonical_digest_drift as test_hydrate_rejects_canonical_digest_drift,
    test_hydrate_rejects_missing_phase5_reference_after_phase5 as test_hydrate_rejects_missing_phase5_reference_after_phase5,
    test_hydrate_rejects_canonical_without_success_record as test_hydrate_rejects_canonical_without_success_record,
)
from tests.terminal_run_continuation_hydration_authority_cases import (
    test_hydrate_rejects_forged_accepted_attempt_id as test_hydrate_rejects_forged_accepted_attempt_id,
    test_hydrate_rejects_resolved_anchor_manifest_mismatch as test_hydrate_rejects_resolved_anchor_manifest_mismatch,
    test_hydrate_rejects_summary_snapshot_drift as test_hydrate_rejects_summary_snapshot_drift,
    test_hydrate_rejects_state_bytes_detached_from_provenance as test_hydrate_rejects_state_bytes_detached_from_provenance,
    test_hydration_state_is_copy_on_read as test_hydration_state_is_copy_on_read,
)
from tests.terminal_run_continuation_regression_cases import (
    test_eligibility_rejects_parent_reused_as_child_id as test_eligibility_rejects_parent_reused_as_child_id,
    test_eligibility_rejects_pass_with_failed_phase as test_eligibility_rejects_pass_with_failed_phase,
    test_eligibility_translates_invalid_storage_boundary as test_eligibility_translates_invalid_storage_boundary,
    test_lock_fstat_failure_does_not_strand_new_owner as test_lock_fstat_failure_does_not_strand_new_owner,
    test_lock_releases_after_caller_finalization_error as test_lock_releases_after_caller_finalization_error,
    test_resolve_accepts_valid_windows_short_path_alias as test_resolve_accepts_valid_windows_short_path_alias,
    test_resolve_eligible_fail_parent as test_resolve_eligible_fail_parent,
)
from tests.terminal_run_continuation_resolve_cases import (
    test_eligibility_rejection_is_read_only_and_calls_no_factories as test_eligibility_rejection_is_read_only_and_calls_no_factories,
    test_eligibility_rejects_anchor_absent_from_summary as test_eligibility_rejects_anchor_absent_from_summary,
    test_eligibility_rejects_incomplete_parent as test_eligibility_rejects_incomplete_parent,
    test_eligibility_rejects_junction_or_symlink_summary_ancestor as test_eligibility_rejects_junction_or_symlink_summary_ancestor,
    test_eligibility_rejects_mismatched_run_identity as test_eligibility_rejects_mismatched_run_identity,
    test_eligibility_rejects_missing_manifest_anchor as test_eligibility_rejects_missing_manifest_anchor,
    test_eligibility_rejects_non_exact_terminal_status as test_eligibility_rejects_non_exact_terminal_status,
    test_eligibility_rejects_relative_and_traversal_summary_paths as test_eligibility_rejects_relative_and_traversal_summary_paths,
    test_eligibility_rejects_workflow_digest_mismatch as test_eligibility_rejects_workflow_digest_mismatch,
    test_eligibility_rejects_workspace_mismatch as test_eligibility_rejects_workspace_mismatch,
    test_resolve_eligible_terminal_parent_uses_explicit_summary as test_resolve_eligible_terminal_parent_uses_explicit_summary,
)
