from tests.run_manifest_baseline_cases import (
    test_child_creation_rejects_parent_contract_mismatch as test_child_creation_rejects_parent_contract_mismatch,
    test_duplicate_namespace_and_readonly_parent_writes_are_refused as test_duplicate_namespace_and_readonly_parent_writes_are_refused,
    test_external_manifest_seals_working_evidence_and_creates_child_lineage as test_external_manifest_seals_working_evidence_and_creates_child_lineage,
    test_interrupted_and_repeated_writes_preserve_previous_manifest as test_interrupted_and_repeated_writes_preserve_previous_manifest,
    test_manifest_models_are_immutable_and_reject_path_traversal as test_manifest_models_are_immutable_and_reject_path_traversal,
    test_open_rejects_schema_version_and_workflow_hash_mismatch as test_open_rejects_schema_version_and_workflow_hash_mismatch,
    test_parent_digest_mutation_and_child_inventory_rewrite_are_refused as test_parent_digest_mutation_and_child_inventory_rewrite_are_refused,
)
from tests.run_manifest_oracle_cases import (
    test_authority_and_child_workspace_must_be_physically_bound as test_authority_and_child_workspace_must_be_physically_bound,
    test_concurrent_same_revision_writers_cannot_both_succeed as test_concurrent_same_revision_writers_cannot_both_succeed,
    test_initial_manifest_cannot_claim_seal_without_real_directory as test_initial_manifest_cannot_claim_seal_without_real_directory,
    test_interrupted_initial_creation_rolls_back_owned_namespace as test_interrupted_initial_creation_rolls_back_owned_namespace,
    test_invalid_model_copy_cannot_replace_readable_manifest as test_invalid_model_copy_cannot_replace_readable_manifest,
    test_readonly_namespace_rejects_windows_junction_escape as test_readonly_namespace_rejects_windows_junction_escape,
    test_retained_writer_cannot_mutate_sealed_parent as test_retained_writer_cannot_mutate_sealed_parent,
    test_seal_and_write_race_cannot_finish_with_successful_unsealed_manifest as test_seal_and_write_race_cannot_finish_with_successful_unsealed_manifest,
    test_working_evidence_rejects_windows_junction_escape as test_working_evidence_rejects_windows_junction_escape,
)
from tests.run_manifest_path_identity_cases import (
    test_non_reparse_directory_attribute_churn_preserves_identity as test_non_reparse_directory_attribute_churn_preserves_identity,
)
from tests.run_manifest_second_oracle_cases import (
    test_direct_context_construction_rejects_authority_inside_workspace as test_direct_context_construction_rejects_authority_inside_workspace,
    test_junction_swap_after_inspection_never_seals_outside_bytes as test_junction_swap_after_inspection_never_seals_outside_bytes,
    test_task2_sources_use_only_python38_syntax_and_runtime_apis as test_task2_sources_use_only_python38_syntax_and_runtime_apis,
)
