from tests.continuation_environment_container_cases import (
    test_ambiguous_framework_ownership_is_rejected as test_ambiguous_framework_ownership_is_rejected,
    test_container_identity_or_runtime_context_mismatch_is_rejected as test_container_identity_or_runtime_context_mismatch_is_rejected,
    test_framework_container_attachment_preserves_owner_and_delete_authority as test_framework_container_attachment_preserves_owner_and_delete_authority,
    test_framework_delete_authority_requires_matching_active_owner_lock as test_framework_delete_authority_requires_matching_active_owner_lock,
    test_released_project_owner_lock_cannot_authorize_deletion as test_released_project_owner_lock_cannot_authorize_deletion,
    test_user_and_external_containers_remain_undeletable as test_user_and_external_containers_remain_undeletable,
)
from tests.continuation_environment_local_cases import (
    test_derived_only_inventory_is_ignored_when_other_identity_matches as test_derived_only_inventory_is_ignored_when_other_identity_matches,
    test_dual_provenance_inventory_accepts_live_matching_observed_hash as test_dual_provenance_inventory_accepts_live_matching_observed_hash,
    test_dual_provenance_inventory_rejects_live_matching_derived_hash_only as test_dual_provenance_inventory_rejects_live_matching_derived_hash_only,
    test_environment_fingerprint_mismatch_is_rejected_before_factories as test_environment_fingerprint_mismatch_is_rejected_before_factories,
    test_exact_host_environment_is_eligible as test_exact_host_environment_is_eligible,
    test_missing_or_non_executable_interpreter_is_rejected as test_missing_or_non_executable_interpreter_is_rejected,
    test_missing_required_environment_is_rejected as test_missing_required_environment_is_rejected,
    test_phase2_may_establish_only_when_parent_never_had_target as test_phase2_may_establish_only_when_parent_never_had_target,
)
