from .v3_environment_output_integration_cases import (
    test_completion_console_renders_runtime_access_and_replay as test_completion_console_renders_runtime_access_and_replay,
    test_summary_telemetry_and_manifest_share_one_runtime_projection as test_summary_telemetry_and_manifest_share_one_runtime_projection,
    test_runtime_reporting_failure_is_diagnostic_and_outcome_neutral as test_runtime_reporting_failure_is_diagnostic_and_outcome_neutral,
    test_unavailable_replay_console_never_prints_success_command as test_unavailable_replay_console_never_prints_success_command,
)
from .v3_environment_output_projection_cases import (
    test_cleanup_failure_is_reported_without_mutating_frozen_outcome as test_cleanup_failure_is_reported_without_mutating_frozen_outcome,
    test_failed_or_unaccepted_attempt_never_becomes_successful_replay as test_failed_or_unaccepted_attempt_never_becomes_successful_replay,
    test_local_fallback_and_missing_probe_are_reported_without_fabrication as test_local_fallback_and_missing_probe_are_reported_without_fabrication,
    test_project_venv_activation_preserves_agent_reported_qualification as test_project_venv_activation_preserves_agent_reported_qualification,
    test_retained_container_reports_exact_access_and_live_replay as test_retained_container_reports_exact_access_and_live_replay,
    test_successful_receipt_with_stopped_container_keeps_replay_unavailable as test_successful_receipt_with_stopped_container_keeps_replay_unavailable,
    test_successful_local_base_environment_reports_authoritative_replay as test_successful_local_base_environment_reports_authoritative_replay,
)
from .v3_environment_output_compatibility_cases import (
    test_legacy_schema_v1_manifest_without_new_container_facts_remains_readable as test_legacy_schema_v1_manifest_without_new_container_facts_remains_readable,
    test_phase2_base_environment_accepts_vendor_metadata_without_venv_claim as test_phase2_base_environment_accepts_vendor_metadata_without_venv_claim,
    test_throwing_runtime_telemetry_cannot_fail_required_existing_hook as test_throwing_runtime_telemetry_cannot_fail_required_existing_hook,
)
from .v3_environment_output_security_cases import (
    test_accepted_attempt_requires_exact_executable_environment_binding as test_accepted_attempt_requires_exact_executable_environment_binding,
    test_accepted_attempt_requires_same_run_environment_binding as test_accepted_attempt_requires_same_run_environment_binding,
    test_accepted_attempt_without_exact_reference_has_no_active_environment as test_accepted_attempt_without_exact_reference_has_no_active_environment,
    test_public_replay_loads_once_and_redacts_secrets_and_controls as test_public_replay_loads_once_and_redacts_secrets_and_controls,
    test_public_replay_redacts_compound_credentials_and_unicode_controls as test_public_replay_redacts_compound_credentials_and_unicode_controls,
    test_tampered_retention_entry_is_derived_from_authenticated_identity as test_tampered_retention_entry_is_derived_from_authenticated_identity,
)
from .v3_environment_output_review_cases import (
    test_generic_manifest_write_cannot_attest_caller_lifecycle as test_generic_manifest_write_cannot_attest_caller_lifecycle,
    test_mismatched_manifest_store_is_rejected_before_projection_or_write as test_mismatched_manifest_store_is_rejected_before_projection_or_write,
    test_partial_runtime_telemetry_failure_keeps_one_projection as test_partial_runtime_telemetry_failure_keeps_one_projection,
    test_phase2_base_environment_accepts_bounded_path_executable as test_phase2_base_environment_accepts_bounded_path_executable,
    test_projection_exception_cannot_skip_required_existing_hook as test_projection_exception_cannot_skip_required_existing_hook,
    test_throwing_existing_telemetry_hook_is_outcome_neutral as test_throwing_existing_telemetry_hook_is_outcome_neutral,
)

__all__ = tuple(name for name in globals() if name.startswith("test_"))
