from tests.resource_manifest_characterization_cases import (
    test_existing_container_characterization_preserves_user_resource as test_existing_container_characterization_preserves_user_resource,
    test_image_backend_characterization_probe_is_read_only as test_image_backend_characterization_probe_is_read_only,
    test_local_backend_characterization_reports_local_without_resource_probe as test_local_backend_characterization_reports_local_without_resource_probe,
    test_phase2_characterization_accepts_report_without_promoting_it as test_phase2_characterization_accepts_report_without_promoting_it,
)
from tests.resource_manifest_authority_cases import (
    test_forged_launcher_executable_requires_framework_capture as test_forged_launcher_executable_requires_framework_capture,
    test_hand_built_error_receipt_cannot_authorize_observation as test_hand_built_error_receipt_cannot_authorize_observation,
    test_hand_built_known_receipt_cannot_authorize_observation as test_hand_built_known_receipt_cannot_authorize_observation,
    test_hand_built_observed_environment_requires_framework_capture as test_hand_built_observed_environment_requires_framework_capture,
)
from tests.resource_manifest_authority_matrix_cases import (
    test_capture_replay_across_run_and_workspace_is_rejected as test_capture_replay_across_run_and_workspace_is_rejected,
    test_coherent_fact_and_receipt_mutation_invalidates_authority as test_coherent_fact_and_receipt_mutation_invalidates_authority,
    test_framework_capture_persists_authenticated_probe as test_framework_capture_persists_authenticated_probe,
    test_fresh_matching_context_reopens_persisted_authority as test_fresh_matching_context_reopens_persisted_authority,
    test_modified_external_capability_fails_closed_on_reopen as test_modified_external_capability_fails_closed_on_reopen,
    test_public_context_has_no_caller_data_signing_oracle as test_public_context_has_no_caller_data_signing_oracle,
    test_top_level_capture_authenticates_launcher_backend_and_opencode as test_top_level_capture_authenticates_launcher_backend_and_opencode,
    test_unsigned_public_normalizers_remain_untrusted as test_unsigned_public_normalizers_remain_untrusted,
)
from tests.resource_manifest_model_cases import (
    test_resource_manifest_exposes_typed_public_contract as test_resource_manifest_exposes_typed_public_contract,
    test_resource_manifest_module_is_available as test_resource_manifest_module_is_available,
)
from tests.resource_manifest_oracle_invariant_cases import (
    test_create_rejects_invalid_initial_manifest_before_write as test_create_rejects_invalid_initial_manifest_before_write,
    test_environment_namespace_matches_container_identity as test_environment_namespace_matches_container_identity,
    test_finalizer_accepts_canonical_manifest_from_short_report_alias as test_finalizer_accepts_canonical_manifest_from_short_report_alias,
    test_local_backend_rejects_container_attachment as test_local_backend_rejects_container_attachment,
    test_phase5_reference_namespace_matches_target_environment as test_phase5_reference_namespace_matches_target_environment,
)
from tests.resource_manifest_oracle_provenance_cases import (
    test_caller_supplied_backend_and_opencode_values_are_not_observed as test_caller_supplied_backend_and_opencode_values_are_not_observed,
    test_changed_namespace_cannot_bypass_probe_promotion as test_changed_namespace_cannot_bypass_probe_promotion,
    test_new_observed_environment_requires_successful_receipt as test_new_observed_environment_requires_successful_receipt,
    test_unknown_receipt_cannot_verify_observed_facts as test_unknown_receipt_cannot_verify_observed_facts,
)
from tests.resource_manifest_oracle_runtime_cases import (
    test_task16_production_path_executes_on_cpython_38 as test_task16_production_path_executes_on_cpython_38,
)
from tests.resource_manifest_reviewer_boundary_cases import (
    test_backend_names_are_typed_variants as test_backend_names_are_typed_variants,
    test_bound_report_directory_accepts_non_reparse_attribute_churn as test_bound_report_directory_accepts_non_reparse_attribute_churn,
    test_local_capture_supports_maximum_environment_id as test_local_capture_supports_maximum_environment_id,
    test_probe_status_rejects_incompatible_fields as test_probe_status_rejects_incompatible_fields,
    test_store_rejects_report_directory_swap as test_store_rejects_report_directory_swap,
    test_task5_export_preserves_short_output_identity as test_task5_export_preserves_short_output_identity,
)
from tests.resource_manifest_reviewer_failure_cases import (
    test_failed_observed_probe_requires_failed_receipt as test_failed_observed_probe_requires_failed_receipt,
    test_failed_observed_probe_with_receipt_persists as test_failed_observed_probe_with_receipt_persists,
    test_initial_failed_observed_probe_with_receipt_persists as test_initial_failed_observed_probe_with_receipt_persists,
)
from tests.resource_manifest_reviewer_provenance_cases import (
    test_container_backend_rejects_foreign_environment_namespace as test_container_backend_rejects_foreign_environment_namespace,
    test_environment_singleton_rejects_conflicting_observation as test_environment_singleton_rejects_conflicting_observation,
    test_initial_observed_environment_requires_receipt as test_initial_observed_environment_requires_receipt,
    test_initial_singleton_fact_rejects_conflicting_value as test_initial_singleton_fact_rejects_conflicting_value,
    test_receipt_cannot_verify_fact_absent_from_environment as test_receipt_cannot_verify_fact_absent_from_environment,
    test_receipt_verified_facts_are_unique as test_receipt_verified_facts_are_unique,
)
from tests.resource_manifest_contract_cases import (
    test_facts_require_bounded_value_provenance_and_exact_namespace as test_facts_require_bounded_value_provenance_and_exact_namespace,
    test_launcher_capture_is_bounded_and_host_observed as test_launcher_capture_is_bounded_and_host_observed,
    test_phase2_report_is_bounded_and_remains_agent_reported as test_phase2_report_is_bounded_and_remains_agent_reported,
)
from tests.resource_manifest_integration_cases import (
    test_duplicate_hook_seal_is_diagnostic_not_outcome_mutation as test_duplicate_hook_seal_is_diagnostic_not_outcome_mutation,
    test_real_local_probe_records_bounded_runtime_without_package_listing as test_real_local_probe_records_bounded_runtime_without_package_listing,
    test_task5_hook_seals_manifest_without_changing_outcome as test_task5_hook_seals_manifest_without_changing_outcome,
)
from tests.resource_manifest_scenario_cases import (
    test_backend_matrix_separates_attachment_ownership_and_lineage as test_backend_matrix_separates_attachment_ownership_and_lineage,
    test_failed_probe_and_remote_opencode_remain_explicit_unknowns as test_failed_probe_and_remote_opencode_remain_explicit_unknowns,
    test_phase5_reference_is_bounded_and_environment_scoped as test_phase5_reference_is_bounded_and_environment_scoped,
    test_probe_distinguishes_base_and_project_environments as test_probe_distinguishes_base_and_project_environments,
)
from tests.resource_manifest_store_cases import (
    test_interrupted_replace_preserves_prior_readable_revision as test_interrupted_replace_preserves_prior_readable_revision,
    test_open_rejects_schema_version_and_run_context_tampering as test_open_rejects_schema_version_and_run_context_tampering,
    test_probe_promotion_requires_receipt_and_retains_report as test_probe_promotion_requires_receipt_and_retains_report,
    test_store_incrementally_writes_and_terminally_seals as test_store_incrementally_writes_and_terminally_seals,
    test_store_rejects_stale_duplicate_and_context_mismatch as test_store_rejects_stale_duplicate_and_context_mismatch,
)
from tests.task5_py38_compat_cases import (
    test_py38_finalizer_isolates_ordinary_exceptions_and_propagates_controls as test_py38_finalizer_isolates_ordinary_exceptions_and_propagates_controls,
    test_real_task5_finalizer_executes_resource_hook_on_cpython_38 as test_real_task5_finalizer_executes_resource_hook_on_cpython_38,
)
from tests.task5_py38_required_stage_cases import (
    test_py38_required_stage_rejected_output_fails_closed as test_py38_required_stage_rejected_output_fails_closed,
)
from tests.resource_manifest_top_level_capture_cases import (
    test_internal_container_backend_and_opencode_capture_persist_and_reopen as test_internal_container_backend_and_opencode_capture_persist_and_reopen,
    test_top_level_capture_rejects_cross_namespace_receipt as test_top_level_capture_rejects_cross_namespace_receipt,
    test_top_level_capture_rejects_duplicate_receipt_identifier as test_top_level_capture_rejects_duplicate_receipt_identifier,
    test_top_level_capture_rejects_omitted_namespace_receipt as test_top_level_capture_rejects_omitted_namespace_receipt,
)
